// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMlx9Qva_b8LvoCQwpnWurxUkS_1tMJ78',
    appId: '1:312479899730:web:33f80a565ff9d2f2487f8b',
    messagingSenderId: '312479899730',
    projectId: 'fir-project1-eb32f',
    authDomain: 'fir-project1-eb32f.firebaseapp.com',
    storageBucket: 'fir-project1-eb32f.appspot.com',
    measurementId: 'G-25W0SEDFG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQyxc6WtNcKiWAw0my8AfAki1lqEoAKTk',
    appId: '1:312479899730:android:1c17449604233f22487f8b',
    messagingSenderId: '312479899730',
    projectId: 'fir-project1-eb32f',
    storageBucket: 'fir-project1-eb32f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO6sMejT-9j46C0RbYEUKGkoLfdIOm5xQ',
    appId: '1:312479899730:ios:0d112dc2fb48208f487f8b',
    messagingSenderId: '312479899730',
    projectId: 'fir-project1-eb32f',
    storageBucket: 'fir-project1-eb32f.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO6sMejT-9j46C0RbYEUKGkoLfdIOm5xQ',
    appId: '1:312479899730:ios:0d112dc2fb48208f487f8b',
    messagingSenderId: '312479899730',
    projectId: 'fir-project1-eb32f',
    storageBucket: 'fir-project1-eb32f.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMlx9Qva_b8LvoCQwpnWurxUkS_1tMJ78',
    appId: '1:312479899730:web:983f71b8224dfa08487f8b',
    messagingSenderId: '312479899730',
    projectId: 'fir-project1-eb32f',
    authDomain: 'fir-project1-eb32f.firebaseapp.com',
    storageBucket: 'fir-project1-eb32f.appspot.com',
    measurementId: 'G-J3TEGJFJ3N',
  );

}